### ISSUE TITLE
description typo

### ISSUE THREAD

**Issue by lkvlkvlkv** [ianian4302/ezTalk_App#1]
無聊人路過看到(?

description 裡面有錯字，應該是 iOS，不是 ios ( 這很重要 )。

附圖：
![image](https://github.com/user-attachments/assets/bb322eb6-9ea7-4f17-9949-dc7dd896f4ef)

**Comment by ianian4302** [comment]
ok 我改一下

怎麼有人在稽查我的github 好害羞

LKV ***@***.***> 於 2024年10月14日 週一 下午3:15 寫道：
